### ISSUE TITLE
response dict items order

### ISSUE THREAD

**Issue by discont** [gerold-penz/python-jsonrpc#16]
Hi,

In some cases order of json items is very important. For example when using api of random.org. It uses a digital signature of returned values. And when you change the order, the signature verification fails. Just look at the small example.

```python
import pyjsonrpc


api_key = '123'

randomorg = pyjsonrpc.HttpClient(url='https://api.random.org/json-rpc/1/invoke')
resp = randomorg.generateSignedIntegers(api_key, 1, 1, 5)

print json.dumps(resp['random'], separators=(',', ':'))
```
result:
>{"min":1,"max":5,"completionTime":"2015-01-03 10:50:22Z","serialNumber":39,"n":1,"base":10,"hashedApiKey":"O8nkxDbtc9xQ4G3czXVKeBRutDIjTrMvXGX82Jc7++3zPPa19cphTdqzYACPlnZsbsoiiYYvFuv3FKh6siqplw==","data":[5],"method":"generateSignedIntegers","replacement":true}

And the correct implementation:
```python
import json
import collections
import requests


api_key = '123'

url = 'https://api.random.org/json-rpc/1/invoke'
headers = {'content-type': 'application/json'}

payload = {
    "method": "generateSignedIntegers",
    "params": {
        "apiKey": api_key,
        "n": 1,
        "min": 1,
        "max": 5,
    },
    "jsonrpc": "2.0",
    "id": 0,
}

resp = requests.post(
    url, data=json.dumps(payload), headers=headers).text

resp = json.loads(resp, object_pairs_hook=collections.OrderedDict)['result']

print json.dumps(resp['random'], separators=(',', ':'))
```
result:
>{"method":"generateSignedIntegers","hashedApiKey":"O8nkxDbtc9xQ4G3czXVKeBRutDIjTrMvXGX82Jc7++3zPPa19cphTdqzYACPlnZsbsoiiYYvFuv3FKh6siqplw==","n":1,"min":1,"max":5,"replacement":true,"base":10,"data":[5],"completionTime":"2015-01-03 10:53:36Z","serialNumber":40}

Sorry for my english.

**Comment by gerold-penz** [comment]
With the new version 0.7.0 of pyjsonrpc, it is possible to change all json.dumps- and json.loads-parameters. This should solve your problem.
See the examples "ordered_dict_example_server.py" and "ordered_dict_example_client.py". 

```python
import pyjsonrpc
import pyjsonrpc.rpcjson
import collections

# JSON settings
pyjsonrpc.rpcjson.loads_object_pairs_hook = collections.OrderedDict

api_key = '123'
randomorg = pyjsonrpc.HttpClient(url='https://api.random.org/json-rpc/1/invoke')
resp = randomorg.generateSignedIntegers(apiKey = api_key, n = 1, min = 1, max = 5)
```
