### ISSUE TITLE
Error codes outside the predefined errors produce a KeyError

### ISSUE THREAD

**Issue by mensonen** [gerold-penz/python-jsonrpc#17]
Hello,

when a JSON-RPC server that conforms to the 2.0 specification returns an error code that is not one of the predefined codes (-32700, -32600, -32601, -32602 or -32603) in rpcerror.py, the pyjsonrpc client throws a KeyError. The specification allows *any* integer to be an error code, but pyjsonrpc implementation expects errors to be one of those five (or None). The error codes should not be restricted to the predefined range (and, in fact, even the cherry-picked five error codes are strange, since the predefined error codes are from -32768 to -32000).

The python-jsonrpc library declares itself as 2.0 conform (it sends jsonrpc version 2.0 to the server), so it should also behave well when parsing the error codes.

If there is any doubt what the allowed errors are, here is one of the JSON-RPC spec authors confirming that *any* integer is an acceptable error code: https://github.com/zendframework/zf2/issues/2456#issuecomment-15134060

Please implement the -32000 to -32099 error code range (reserved server errors) and also allow any integer code outside -32768 to -32000 as well (it would be enough just to raise a generic JsonRpcError ).

**Comment by belussi** [comment]
Hi,

I`m also facing this issue. I need to add server defined exception...Guys, Are you going to do something with this?

**Comment by OrangeTux** [comment]
I've created a pull request: #20.

**Comment by gerold-penz** [comment]
Now you can use any integer as error code.
