### ISSUE TITLE
Set custom headers for cgi

### ISSUE THREAD

**Issue by armandokeller** [gerold-penz/python-jsonrpc#18]
Hello, I'm using the handle_cgi_request method, but I need to use custom headers like "Access-Control-Allow-Origin" to enable the cross-domain feature.
I tried to add they in line 495 of http.py as : 
print   "Access-Control-Allow-Origin: *"

but there is no effect.

**Comment by gerold-penz** [comment]
Your change should give the desired result. If not: try to add this header with the HTTP-server (apache, nginx, ...) itself.
