### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by hapasa** [gerold-penz/python-jsonrpc#19]
After a cursor look there does not seem to be Python3 support.
It would be nice to have to be able to interoperate with https://github.com/aaugustin/websockets 
The latter relies on asyncio which looks like a nice package for Python 3.4

Hence the request, add Python3 support

**Comment by gerold-penz** [comment]
I have no experience with Python 3. Sorry, but Python 3 support is currently not an option.

**Comment by scls19fr** [comment]
You might install Anaconda Python so you can easily have a Python 2 and a Python 3 environment.
see http://continuum.io/blog/anaconda-python-3

Six can help http://pythonhosted.org/six/

**Comment by hapasa** [comment]
I took a quick look at the issues why python3 would not work and problems are at library level.  http support, urllib etc., so automated conversion is unlikely to cut it.

I switched to json-rpc (pip3 install json-rpc), and it was straight forward to add support to it for requests, bottle, websockets coming up.

Time to ditch python 2 for me, on library level python 3 is better.,,

**Comment by scls19fr** [comment]
see also https://github.com/gerold-penz/python-jsonrpc/issues/28
