### ISSUE TITLE
Named Paramater With Special Characters Broken

### ISSUE THREAD

**Issue by chris-barry** [gerold-penz/python-jsonrpc#23]
Problem: [see title]

Code: https://github.com/gerold-penz/python-jsonrpc/blob/master/examples/http_client_usage/ordered_dict_example_client.py#L18-L27

Got: `{"params": [{"a": "AAA", "c": "CCC", "b": "BBB", "e": "EEE", "d": "DDD", "g": "GGG", "f": "FFF"}], "jsonrpc": "2.0", "method": "format_text", "id": "d7ca5d91-bede-44be-93d7-21ea7d739cd2"}`

Expected: `{"params": {"a": "AAA", "c": "CCC", "b": "BBB", "e": "EEE", "d": "DDD", "g": "GGG", "f": "FFF"}, "jsonrpc": "2.0", "method": "format_text", "id": "d7ca5d91-bede-44be-93d7-21ea7d739cd2"}`

Reference:http://www.jsonrpc.org/specification#examples

**Comment by gerold-penz** [comment]
Hello cris-barry!

The example, to which you refer, sends one *positional* argument. *Positional* arguments are JavaScript-arrays. Only *named* parameters will be transfered as JavaScript-objects. JavaScript-objects are not ordered. Same like Python dictionaries.
I think, my implementation does the right. I don't want implicitly change the behavior.

regards,
Gerold

**Comment by chris-barry** [comment]
I feel we are misunderstanding eachother? To clarify, I was unable to send named paramters, not positional. The positional parameters work as expected from what I can tell. The example in the JSON-RPC2.0 spec shows that a named parameter would be sent like this:

    --> {"jsonrpc": "2.0", "method": "subtract", "params": {"subtrahend": 23, "minuend": 42}, "id": 3}
    <-- {"jsonrpc": "2.0", "result": 19, "id": 3}

Currently, your code sends an array of a single item. Am I missing the proper way to send named parameters?

**Comment by gerold-penz** [comment]
```python
import pyjsonrpc
rpc_client = pyjsonrpc.HttpClient(...)
print rpc_client.subtract(subtrahend = 23, minuend = 42)
```

**Comment by chris-barry** [comment]
This method does not work when the names contain dots. (I should have mentioned that was my issue).
-- 
Chris Barry

**Comment by gerold-penz** [comment]
Server:

```python
class RequestHandler(pyjsonrpc.HttpRequestHandler):
    @pyjsonrpc.rpcmethod
    def subtract(self, minuend, subtrahend):
        return minuend - subtrahend
```

**Comment by gerold-penz** [comment]
Ahhhhh! The dots in the keys is your problem. The parameter names must be clean. But you can pass a dictionary or ordered dictionary. See next comment (in some minutes).

**Comment by gerold-penz** [comment]
Server:

```python
class RequestHandler(pyjsonrpc.HttpRequestHandler):
    @pyjsonrpc.rpcmethod
    def format_it(self, keys_and_values):
        retstr = u""
        for key, value in keys_and_values.items():
            retstr += u"{key}: {value}\n".format(key = key, value = value)
        return retstr
```

**Comment by gerold-penz** [comment]
```python
rpc_client = pyjsonrpc.HttpClient(...)
print rpc_client.format_it(
    keys_and_values = {
        "a.b": "A.B",
        "c.d": "C.D",
    }
)
```

**Comment by gerold-penz** [comment]
Client 2:

```python
print rpc_client.format_it({
    "a.b": "A.B",
    "c.d": "C.D",
})
```

**Comment by chris-barry** [comment]
Awesome! I really appreciate the assistance. :)

Now for my other issue, which I am confident is fixed properly. Passing custom ssl_context. If I remove 8cee2b7 from PR #23, does the PR look good? Meaning it would include 1861ca5 and 0d2e231 .

**Comment by chris-barry** [comment]
After looking into this issue more, I am back to believing that you have it implemented incorrectly. While the solution works when you control the server, it does not when working with pre-existing ones.

There must be a way to send named parameters with special characters not as a single item, but as named parameters. For example, lets say I need to send the parameters,  'a.a' and 'b.b' to a pre-existing implementation which I cannot change:

```python
pyjsonrpc.create_request_json("add", {'a.a':'1','b.b':'2'})
# >>> '{"params": [{"b.b": "2", "a.a": "1"}], "jsonrpc": "2.0", "method": "add", "id": "d072bed4-f830-43fe-8667-38dcff1ed434"}'
#
# Most would expect:
# >>> '{"params": {"b.b": "2", "a.a": "1"}, "jsonrpc": "2.0", "method": "add", "id": "d072bed4-f830-43fe-8667-38dcff1ed434"}'
```
