### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by gerold-penz** [gerold-penz/python-jsonrpc#28]
https://docs.python.org/3/howto/pyporting.html

**Comment by scls19fr** [comment]
I noticed you are using Bunch
A Bunch package for Python 3 is necessary.

you might have a look at
https://github.com/dsc/bunch/
https://github.com/dsc/bunch/network

I think all these forks need first to be merged before considering a Python 3 version of `python-jsonrpc`.

An other approach could be to avoid to use Bunch.

**Comment by scls19fr** [comment]
Effort to port `python-jsonrpc` from Python 2 to Python 3 might first be to create some unit tests.

You should use either 
- standard unit tests https://docs.python.org/2/library/unittest.html
- nosetests https://nose.readthedocs.org/
- pytest http://pytest.org/

nosetests and pytests are easy to write (much easier in my mind than standard unittest)
but I haven't write tests in client/server.

After unit tests, it can be interesting to have continuous integration.

Travis travis-ci.org/ might help.
It's free for open source projects.
It will help to ensure that package it correct and that unit tests don't fail.

An other important part could be to ensure code quality.
Landscape.io https://landscape.io/ is a very interesting service for this.
You can add landscape.io in less than 1 minute and it will provide very interesting.

A last part could be to add code coverage
Coveralls might help https://coveralls.io/
https://godjango.com/25-travis-ci-and-coveralls/

**Comment by gerold-penz** [comment]
Hi scls19fr!
For now, "python-jsonrpc" works fine for my need. Sorry, but I have not the time to learn Python 3. In a few years maby.
Regards

**Comment by scls19fr** [comment]
Why ???

I send you a PR to make some unit tests that is merged
You have PR to help you https://github.com/gerold-penz/python-jsonrpc/pull/39
if this PR break your code it won't pass continuous integration.

You are not alone!

Python 3 is becoming better and better (and MUCH better that Python 2)
