### ISSUE TITLE
Exception raised when None returned

### ISSUE THREAD

**Issue by F483** [gerold-penz/python-jsonrpc#32]
RPC Methods that return None raise an Error. Having a function return None is the default python behaviour when return is not used and often a desired result for a function.

I expect the rpc interface to behave as follows:

    rpc_return_data = json.loads(json.dumps(method_return_data))

The error:

    In [1]: import pyjsonrpc                                                    
                                                                                
    In [2]: rpc = pyjsonrpc.HttpClient(url = "http://localhost:8080")           
                                                                                
    In [3]: rpc.test()                                                          
    --------------------------------------------------------------------------- 
    InternalError                             Traceback (most recent call last) 
    <ipython-input-3-6f90dda2590b> in <module>()                                
    ----> 1 rpc.test()                                                          
                                                                                
    /home/fabe/dev/apigen/env/py2/lib/python2.7/site-packages/python_jsonrpc-0.7.7-py2.7.egg/pyjsonrpc/http.pyc in __call__(self, *args, **kwargs)
        158                                                                     
        159         def __call__(self, *args, **kwargs):                        
    --> 160             return self.http_client_instance.call(self.method, *args, **kwargs)
        161                                                                     
        162                                                                     
                                                                                
    /home/fabe/dev/apigen/env/py2/lib/python2.7/site-packages/python_jsonrpc-0.7.7-py2.7.egg/pyjsonrpc/http.pyc in call(self, method, *args, **kwargs)
        262                     raise rpcerror.jsonrpcerrors[response.error.code](
        263                         message = response.error.message,            
    --> 264                         data = response.error.data                  
        265                     )                                               
        266                 else:                                               
                                                                                
    InternalError: JsonRpcError(-32603): Internal JSON-RPC error.

**Comment by gerold-penz** [comment]
Hello F483!
I think you are right. I change de behavior now. Hopefully to not crash existing programs.

**Comment by gerold-penz** [comment]
done

**Comment by F483** [comment]
Thank you very much!!
