### ISSUE TITLE
Should I fork due to lacking python 3 support and an uncooperatave maintainer?

### ISSUE THREAD

**Issue by F483** [gerold-penz/python-jsonrpc#40]
Python 3 has been around for many years and is now becoming the standard over python 2. All the software I and many others write is python 2 and 3 compatible. I currently depend on python-jsonrpc in several places and need python 3 support.

@gerold-penz has repeatedly stated that he has no interest in supporting python 3.

> Since I don't need Python 3 support (in the next 1 or 2 years), I can not spend time to adapt python-jsonrpc to Python 3.

Has closed several issues regarding python 3 support:
- https://github.com/gerold-penz/python-jsonrpc/issues/28
- https://github.com/gerold-penz/python-jsonrpc/issues/19
- https://github.com/gerold-penz/python-jsonrpc/issues/25

It's all fine and good if he is not willing to support it himself, after all it is free software and he has no responsibility to us. I am very thank full for the work he has done. 

I offered to port and maintain the python 3 code myself and have done almost all of it already https://github.com/gerold-penz/python-jsonrpc/pull/39, however he has also closed this pull request.

This only tells me he has no interest in others users apart from himself and is not willing to let it grow, so that it can be useful to others and have other users contribute.

In the coming days I will look into changing my libs to use another lib or forking this project altogether if nothing about this changes, as a python 2 only lib is not useful in the year 2015.

CC @scls19fr @hapasa @hapasa @femtotrader

**Comment by super3** [comment]
Changes to support Python 3 in addition to Python 2 are minimal. Just about every major project already supports Python 3, or is actively working on it. This isn't progressive, its catch-up at this point. 

I agree that if @gerold-penz doesn't want to support Python 3, the repo should be forked to support both.

**Comment by scls19fr** [comment]
supporting Python 2 & 3 will be great.

A fork which belongs to an org will a good idea.

**Comment by scls19fr** [comment]
Munch can replace Bunch
https://github.com/Infinidat/munch
for Python 2/3 support

**Comment by fake-name** [comment]
Holy crap, I started porting to this library not even *considering* that it wouldn't support python 3 (it's been 7 years).

**Comment by gerold-penz** [comment]
Hi, currently I have absolute no time to learn Python 3. So this library will not support Python 3 in the next few years.

**Comment by fake-name** [comment]
@gerold-penz - You have at least one person in this thread who appears to be interested in helping with maintenance. Why not let other people help?
