### ISSUE TITLE
"notify" function does not work with server running C++ JSON RPC

### ISSUE THREAD

**Issue by brandonkimbk** [gerold-penz/python-jsonrpc#41]
I am currently trying to interface with a C++ JSON RPC server (https://github.com/cinemast/libjson-rpc-cpp) over http and found that the notify function does not work. However, I believe I have found the problem.

 I am not sure if the interpretation of "Notification" in JSON 2.0 is up for debate (http://www.jsonrpc.org/specification#notification) but it seems while this python library simply puts **None** for the "id" member in the request_dict, the C++ library is expecting there to be no "id" item in the payload at all.

I got around this problem by editing _lines 294 and 299 in 'http.py'_ with **del request_dict["id"]** instead. I'm not sure if this is really the right fix for this problem and I have not tested to see if this would work with the server running on python.

**Comment by gerold-penz** [comment]
Hi! That's a real problem. You are right: Notifications must not have an "id"-field. I think about it.
