### ISSUE TITLE
Can we support python 3?

### ISSUE THREAD

**Issue by feixia586** [gerold-penz/python-jsonrpc#43]
Hi, I am actively using this package and I am now switching to python 3. Can we also support python 3? I think it would benefit a lot of developers. Thank you!

**Comment by gerold-penz** [comment]
Hi, currently I have absolute no time to learn Python 3. So this library will not support Python 3 in the next few years.

**Comment by scls19fr** [comment]
Related issue https://github.com/gerold-penz/python-jsonrpc/issues/40
