### ISSUE TITLE
Additional control of serialization/deserialization

### ISSUE THREAD

**Issue by geerk** [gerold-penz/python-jsonrpc#9]
It would be great to have a possibility to control parameters of `dumps`/`loads` methods of `json` library. Especially specifying `JSONEncoder` class would be very usefull. For example now I need to serialize `Decimal` values, but can't customize `dumps` behaviour.

Thanks for your work.

**Comment by gerold-penz** [comment]
With the new version 0.7.0 of *pyjsonrpc*, it is possible to change all *json.dumps*- and *json.loads*-parameters.
See the examples "ordered_dict_example_server.py" and "ordered_dict_example_client.py".

**Comment by geerk** [comment]
@gerold-penz thank you!
